### ISSUE TITLE
数次操作以后窗口会变得越来越小，而且还不能调大小

### ISSUE THREAD

**Issue by EvanBranty** [Hgnim/TimedPower#1]
（系统是win11）∠( ᐛ 」∠)_
![countdownerror 00_00_00-00_00_30](https://github.com/Hgnim/TimedPower/assets/52557408/cacca718-9c6a-4b39-894e-39b7ebbe4973)

**Comment by Hgnim** [comment]
已在[V1.2.2.20240703](https://github.com/Hgnim/TimedPower/releases/tag/V1.2.2.20240703)版本中修复，如果问题仍没解决，请及时反馈。:)
