### ISSUE TITLE
开机后自启动倒计时

### ISSUE THREAD

**Issue by dava123510** [Hgnim/TimedPower#2]
开机后自启动，进行关机倒计时.

**Comment by Hgnim** [comment]
最新版本已发布，已实现所述功能。
目前新功能处于测试阶段，如果遇到bug请及时汇报
[软件v2.2.2版本下载](https://github.com/Hgnim/TimedPower/releases/tag/V2.2.2.20240918)
enjoy :)

**Comment by dava123510** [comment]
我使用这个项目是为了远程做游戏任务项目结束后就行关机，前些时间，那个项目的设置里有做完任务关机，如果是因为游戏更新等无法完成任务就不能做到关机，需要这个项目来解决，我的想法是自启动这个项目后倒计时自主运行不需要人为点击
![173a8c631197e07b3f7cf50e71a7e3d4](https://github.com/user-attachments/assets/281ed097-da6d-4055-bc33-30bfd9fffbbd)
我最近开始摸索着怎么用，也许是上次表达不当抱歉了，如果已解决此问题求教程谢谢了。谢谢了

**Comment by Hgnim** [comment]
首先确保使用的[软件版本](https://github.com/Hgnim/TimedPower/releases/tag/V2.3.4.20241029)包含此功能

右键软件空白处，如下图所示启用程序的开机自启动
![](https://github.com/user-attachments/assets/ff53a0d6-2c5d-43c0-8f0f-df3c13f8f344)

再次右键软件空白处，点击```自动定时任务```按钮
![](https://github.com/user-attachments/assets/2cd2b0c1-5db9-4d14-99df-633f59be810a)

打开自动定时任务窗口后，新建并设置所需要执行的定时任务后，启用并保存即可
![](https://github.com/user-attachments/assets/6011eb46-0299-4e1d-a5a2-3ce0a624511e)

**Comment by dava123510** [comment]
我需要的是开机自动关机emmm，不是定时关机，就是开机作为触发，然后一段时间后关机，因为我不能在我的电脑旁，所以我的开机时间不是定时的
![05fe5c8e1394268757e9a354be64fb2c](https://github.com/user-attachments/assets/7cf89f07-475b-4922-83f6-c7cb9438a657)

**Comment by Hgnim** [comment]
好的明白，此功能将在不久后推出

**Comment by dava123510** [comment]
谢谢作者的积极回复

**Comment by Hgnim** [comment]
所需功能已在[该版本](https://github.com/Hgnim/TimedPower/releases/tag/V2.4.4.20241117)中实现
